server:
  port: 8080

spring:
  application.name: course-web
  datasource:
    url: jdbc:h2:mem:coursedb
    username: yu7i
    password: 53cret

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

  liquibase:
    enabled: false
