server:
  port: 8080

spring:
  application.nam: course-web
  datasource:
    url: jdbc:h2:mem:coursedb

  jpa:
    show-sql: true
    hibernate:
      #      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update

  liquibase:
    enabled: false
